#!/bin/sh

# get my extern IP address
#

if [ "$1" == "" ]
then
#	curl https://ipinfo.io/ip
	curl -s http://checkip.amazonaws.com/
elif [ "$1" == "-a" ]
then
        curl https://ipinfo.io/
else
        echo `basename $0` [-a]
fi
